# Site settings
title: Star Lake
email: binary59@gmail.com
#description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
#url: "http://starlakes.tk"

# Build settings
#pygments: true
#markdown: rdiscount
markdown: kramdown
permalink: pretty
